jobs:

- job: Dotnet
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: DotNetCoreCLI@2
    inputs:
      command: test
      projects: '**/*.Test.csproj'
      arguments: '--configuration Release'

- job: Go
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - script: go test ./...
