pool:
  vmImage: 'Ubuntu 16.04'

steps:

- task: DotNetCoreCLI@2
  inputs:
    command: test
    projects: 'dotnet/**/*.Test.csproj'
    arguments: '--configuration Release'
  displayName: 'Build and test in .NET Core'